medicover/urls.py
from django.contrib import admin
from django.urls import path, include , re_path
from django.views.generic import TemplateView, RedirectView
from django.contrib.staticfiles.urls import  staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    re_path(r'^$',RedirectView.as_view(url='school')),
    path('accounts/',include('accounts.urls')),
    path('school/', include('school.urls')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG :
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = 'medicover.views.handler404'
handler500 = 'medicover.views.handler500'

school/urls.py
from django.conf.urls import url
from school import views as music_views


app_name = "school"

urlpatterns = [

    url(r'^$', music_views.dashboard, name='dashboard'),
    url(r'^login/$', music_views.login_user, name='login'),
    url(r'^register/$', music_views.register, name='register'),
    url(r'^logout/$', music_views.logout_user, name='logout'),
    url(r'^teachers/$', music_views.teachers, name='teachers'),
    url(r'^students/$', music_views.students, name='students'),
    url(r'^books/$', music_views.books, name='books'),
    url(r'^profile/$', music_views.profile, name='profile'),
]

school/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.forms import model_to_dict
from django.shortcuts import render

from accounts.forms import LoginForm, UserForm, TeacherForm, StudentForm, BookForm
from accounts.models import User, Book

from django.shortcuts import redirect

import logging

log = logging.getLogger(__name__)


def dashboard(request):
    if not request.user.is_authenticated:
        return redirect('school:login')
    # return render(request,'school/dashboard.html')
    if request.user.is_principal:
        return redirect('school:teachers')
    elif request.user.is_teacher:
        return redirect('school:students')
    else:
        return redirect('school:books')


def logout_user(request):
    logout(request)
    return redirect('school:login')


def login_user(request):
    form = LoginForm(request.POST or None)

    context = {
        'form': form
    }

    if request.user.is_authenticated:
        return redirect('school:index')

    if request.method == "POST":

        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect('school:dashboard')
                # return render(request, 'school/dashboard.html',{'albums':albums})
            else:
                context.update({'error_message': 'Your account has been disabled'})
                return render(request, 'school/login.html', context)
        else:
            context.update({'error_message': 'Invalid username or Password.'})
            return render(request, 'school/login.html', context)

    return render(request, 'school/login.html', context)


def register(request):
    form = UserForm(request.POST or None)

    context = {
        "form": form,
    }

    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            # user_data = {'username': username, 'email': email, 'password': password}
            user = User(username=username, email=email)
            user.set_password(password)
            user.save()
            user = authenticate(username=email, password=password)
            if user:
                login(request, user)
                return redirect('school:dashboard')
        except Exception as e:
            log.error(e.args)
            # context.update({'error_message':'user already exists ...'})
            return render(request, 'school/register.html', context)

    return render(request, 'school/register.html', context)


@login_required
def profile(request):
    return render(request, 'school/profile.html')


def get_teachers_with_students(loginuser):
    users = User.objects.filter(is_teacher=True, created_by=loginuser)
    teachers = []
    for user in users:
        teacher = model_to_dict(user)
        students = [model_to_dict(student)
                    for student in User.objects.filter(is_student=True, created_by=user)]
        teacher['students'] = students
        teachers.append(teacher)
    return teachers


def get_students_with_books(loginuser):
    if loginuser.is_principal:
        users = User.objects.filter(is_student=True,
                                    created_by__in=User.objects.filter(is_teacher=True, created_by=loginuser))
    else:
        users = User.objects.filter(is_student=True, created_by=loginuser)
    students = []
    for user in users:
        student = model_to_dict(user)
        books = [model_to_dict(student)
                    for student in Book.objects.filter(user=user)]
        student['books'] = books
        students.append(student)
    return students


@login_required
def teachers(request):
    form = TeacherForm(request.POST or None)

    context = {
        "form": form,
        'teachers': get_teachers_with_students(request.user)
    }

    if request.method == 'POST':
        password = request.POST.get('password')
        if form.is_valid():
            print(form.cleaned_data)
            teacher = form.save(commit=False)
            teacher.set_password(password)
            teacher.is_principal = False
            teacher.profile_picture = request.FILES['profile_picture']
            teacher.created_by = request.user
            teacher.save()
            context.update({'teachers': get_teachers_with_students(request.user)})
        else:
            context.update({'errors': form.errors})
            return render(request, 'school/add_teacher.html', context)

    return render(request, 'school/add_teacher.html', context)


@login_required
def students(request):
    form = StudentForm(request.POST or None)

    context = {
        "form": form,
        'students': get_students_with_books(request.user)
    }

    if request.method == 'POST':
        password = request.POST.get('password')
        if form.is_valid():
            print("add", form.cleaned_data)
            student = form.save(commit=False)
            student.set_password(password)
            student.profile_picture = request.FILES['profile_picture']
            student.is_principal = False
            student.created_by = request.user
            student.save()
            context.update({'students': get_students_with_books(request.user)})
        else:
            print(form.errors)
            context.update({'errors': form.errors})

    return render(request, 'school/add_students.html', context)


@login_required
def books(request):
    form = BookForm(request.POST or None)

    context = {
        "form": form,
        'books': Book.objects.filter(user=request.user)
    }

    if request.method == 'POST':

        if form.is_valid():
            print("add", form.cleaned_data)
            book = form.save(commit=False)
            book.user = request.user
            book.save()
            context.update({'books': Book.objects.filter(user=request.user)})
        else:
            print(form.errors)
            context.update({'errors': form.errors})

    return render(request, 'school/add_books.html', context)

templates/school/add_books.html
{%extends 'base.html'%} {% block content %}
{% load static %}
<body>
    <!-- Main container-->
    <div class="app-container">
        <!-- top navbar-->
        <header class="bg-primary">
            <!-- START Top Navbar-->
            {% include 'school/navbar.html' %}
            <!-- END Top Navbar-->
        </header>
        <!-- Sidebar-->
       {% include 'school/sidenav.html' %}
        <!-- Main-->


        <section>
            <!-- Content-->
            <div class="app">
            {%  if errors %}
                <div class="text-gray-darker">
                {{ errors }}
                </div>
            {% endif %}
                <div class="container">

                    <!-- Modal -->
                    <div class="modal fade" id="album_form" role="dialog">
                        <div class="modal-dialog">

                            <!-- Modal content-->
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                    <h4 class="modal-title">Add Books</h4>
                                </div>
                                <div class="modal-body">
                                    <div id="album-id-form" class="bg-white" style="padding-top: 5rem;margin-left: 15px;margin-right: 15px;padding-right: 2rem;padding-bottom: 1rem;">
                                        <form method="post" action="{% url 'school:books' %}" class="form-horizontal" enctype="multipart/form-data">
                                             {% csrf_token %}
                                            <fieldset>
                                                <div class="form-group">
                                                    <label for="input-id-1" class="col-sm-2 control-label">Author</label>
                                                    <div class="col-sm-10">
                                                        <input id="input-id-1" name="name" type="text" class="form-control shadow-z1" required>
                                                    </div>
                                                </div>
                                            </fieldset>
                                            <fieldset>
                                                <div class="form-group">
                                                    <label for="input-id-1" class="col-sm-2 control-label">Class</label>
                                                    <div class="col-sm-10">
                                                        <select name="tclass" id="input-id-1" class="form-control shadow-z1">
                                                            <option value="10th" selected>10th</option>
                                                            <option value="9th">9th</option>
                                                            <option value="8th">8th</option>
                                                            <option value="7th">7th</option>
                                                            <option value="6th">6th</option>
                                                            <option value="5th">5th</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </fieldset>
                                            <fieldset>
                                                <div class="form-group">
                                                    <label class="col-sm-2 control-label">Subject</label>
                                                    <div class="col-sm-10">
                                                        <input type="text" name="subject" class="form-control shadow-z1" required="required">
                                                    </div>
                                                </div>
                                            </fieldset>
                                            <div class="form-group text-center">
                                                <button type="submit" class="mr btn btn-oval btn-default">Add</button>

                                                <button type="button" class="mr btn btn-oval btn-default" data-dismiss="modal">Close</button>
                                            </div>

                                        </form>
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>

                </div>

                <div class="app-view-header col-md-12">
                    <span class="text-left">Books</span>
                    <span style="float:right">
                        <button type="button" class="mr btn btn-lg btn-circle btn-primary" data-toggle="modal" data-target="#album_form">
                            <em class="fa fa-plus"></em>
                        </button>

                    </span>

                </div>

                <div class="row">
                    <!-- START dashboard content-->



                    <div class="col-lg-6 fw-boxed" style="padding-top:1rem">
                        <!-- START Tabbed panel-->


                        <div class="row">

                            {% for book in books %}
                            <div class="col-md-4 col-xs-12">
                                <!-- START Panel-->
                                <div data-chained-animation="fadeInUp" class="album-card panel panel-card panel-card-image bg-warning animated fadeInUp"
                                    style="
                                background-image: url('https://www.clker.com/cliparts/6/4/J/9/E/9/closed-book-hi.png');
                                " data-toggle="modal" data-target="#album_form_{{ loop.index }}">
                                    <div class="panel-body text-center">
                                        <h4 class="text-white">{{ book.subject}}</h4>
                                        <h2 class="text-lg text-white"> {{ book.tclass }}</h2>
                                        <small class="text-white">{{ book.name }}</small>
                                    </div>
                                </div>
                                <div class="container">

                                    <!-- Modal -->
                                    <div class="modal fade" id="album_form_{{ loop.index }}" role="dialog">
                                        <div class="modal-dialog">

                                            <!-- Modal content-->
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                                                    <h4 class="modal-title">Book Details</h4>
                                                </div>
                                                <div class="modal-body">
                                                    <div>
                                                    <h2>{{ book.subject }}</h2>
                                                    <span>
                                                        <strong>Class: </strong> {{ book.tclass }}. </p>
                                                        </span>
                                                            <strong>Author: </strong> {{ book.name }} </p>

                                                    </div>
                                                    <div class="text-center">
                                                <figure>
                                                    <img src="{{ teacher.profile_picture.url }}" height="200" width="200" alt="" class=" img-responsive">
                                                    <figcaption class="ratings">
                                                        <p>Ratings
                                                            <a href="#">
                                                                <span class="fa fa-star"></span>
                                                            </a>
                                                            <a href="#">
                                                                <span class="fa fa-star"></span>
                                                            </a>
                                                            <a href="#">
                                                                <span class="fa fa-star"></span>
                                                            </a>
                                                            <a href="#">
                                                                <span class="fa fa-star"></span>
                                                            </a>
                                                            <a href="#">
                                                                <span class="fa fa-star-o"></span>
                                                            </a>
                                                        </p>
                                                    </figcaption>
                                                </figure>
                                            </div>

                                                </div>

                                            </div>

                                        </div>
                                    </div>

                                </div>
                                <!-- END Panel-->
                            </div>
                            {% endfor %}

                        </div>


                    </div>

                </div>
            </div>
        </section>
        <!-- Page footer-->
        <footer>
            <span>&copy; 2015 - Application Name</span>
        </footer>
    </div>
</body>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        $(document).on('click', '.browse', function () {
            var file = $(this).parent().parent().parent().find('.file');
            file.trigger('click');
        });
        $(document).on('change', '.file', function () {
            $(this).parent().find('.form-control').val($(this).val().replace(/C:\\fakepath\\/i, ''));
        });

        $(document).on('ready', function () {

            //$('.album-card2').append(($('.album-card')[0]).cloneNode());
            $(function() { 
        // Setup the player to autoplay the next track
        var a = audiojs.createAll({
          trackEnded: function() {
            var next = $('ol li.playing').next();
            if (!next.length) next = $('ol li').first();
            next.addClass('playing').siblings().removeClass('playing');
            audio.load($('a', next).attr('data-src'));
            audio.play();
          }
        });
        
        // Load in the first track
        var audio = a[0];
            first = $('ol a').attr('data-src');
        $('ol li').first().addClass('playing');
        audio.load(first);

        // Load in a track on click
        $('ol li').click(function(e) {
          e.preventDefault();
          $(this).addClass('playing').siblings().removeClass('playing');
          audio.load($('a', this).attr('data-src'));
          audio.play();
        });
        // Keyboard shortcuts
        $(document).keydown(function(e) {
          var unicode = e.charCode ? e.charCode : e.keyCode;
             // right arrow
          if (unicode == 39) {
            var next = $('li.playing').next();
            if (!next.length) next = $('ol li').first();
            next.click();
            // back arrow
          } else if (unicode == 37) {
            var prev = $('li.playing').prev();
            if (!prev.length) prev = $('ol li').last();
            prev.click();
            // spacebar
          } else if (unicode == 32) {
            audio.playPause();
          }
        })
      });
        });

        $('.sidebar-toggle-off').on('click',function(){
                if ($('body').hasClass("aside-offscreen")){
                    $('.album-card2').css("padding-right","5rem");
                }
                else{
                    $('.album-card2').css("padding-right","0rem");
                }
            
        });

    }, false);

</script> {% endblock %}

templates/school/form_login.html
<div class="row">
    <div class="col-md-6">

        {% for field in form %}
        <div class="form-group has-feedback mb">
            {{ field }} {% if field.html_name == "username" %}
            <span class="fa fa-user form-control-feedback text-muted"></span> {% elif field.html_name == "password" %}
            <span class="fa fa-lock form-control-feedback text-muted"></span> {% endif %}
        </div>
        <div class="form-group has-error" style="color:red">
            {{ field.errors }}
        </div>

        {% endfor %}
        <div class="checkbox c-checkbox pull-left mt0">
            <label>
<input type="checkbox" value=""><span class="fa fa-check"></span> Remember me
</label>
        </div>
    </div>
    <div class="col-md-6">
        <button type="submit" class="btn btn-block btn-info mb">Login</button>
        <p class="text-muted mb0">Don't have an account yet?</p><a href="{% url 'school:register' %}" class="btn btn-block btn-default"><strong>Register one</strong></a>
    </div>
</div>

templates/school/form_register.html
<div class="row">
    <div class="col-md-6">
        {% for field in form %}
        <div class="form-group has-feedback">
            {{ field }} {% if field.html_name == "username" %}
            <span class="fa fa-user form-control-feedback text-muted"></span> {% elif field.html_name == "email" %}
            <span class="fa fa-envelope form-control-feedback text-muted"></span> {% elif field.html_name == "password" %}
            <span class="fa fa-lock form-control-feedback text-muted"></span> {% elif field.html_name == "confirm_password" %}
            <span class="fa fa-lock form-control-feedback text-muted"></span> {% endif %}
        </div>
        <div class="form-group has-error" style="color:red">
            {{ field.errors }}
        </div>

        {% endfor %}
        <div class="clearfix">
            <div class="checkbox c-checkbox pull-left mt0">
                <label>
                        <input type="checkbox" value=""><span class="fa fa-check"></span> I agree with the <a href="#">terms</a>
                    </label>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <button type="submit" class="btn btn-block btn-primary">Create account</button><br>
        <p class="pt-lg text-center mt-sm">Already register?</p><a href="{% url 'school:login'%}" class="btn btn-block btn-default"><strong>Login</strong></a>
    </div>
</div>

templates/school/login.html
{% extends 'base.html'%} {% block content%}

<body>
    <div class="animated fadeOutZoom">
        <div class="container container-sm animated fadeInDown">
            <div class="center-block mt-xl">
                <!-- START panel-->
                <h3 style="text-align:center">Medicover School</h3>
                <div class="panel">
                    <div class="panel-body">
                        <p class="pv text-bold">LOGIN CREDENTIALS</p>
                        <div class="form-group has-error">
                            <label class="control-label" style="color:coral">{{ error_message }}</label>
                        </div>

                        <form role="form" class="mb-lg" method="post" action="{% url 'school:login' %}">
                            {% csrf_token %} {% include 'school/form_login.html' %}
                        </form>
                    </div>
                </div>
                <div class="text-center mt"><a href="javascript:void(0)" class="text-muted">Forgot your password?</a></div>
                <!-- END panel-->
                <div class="p-lg text-center">
                    <hr><span class="mr-sm">&copy; </span><span class="mr-sm">2015</span><span>Naut</span><br>Bootstrap + AngularJS
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

templates/school/navbar.html
<nav role="navigation" class="navbar topnavbar">
                <!-- START button offset-->
                <div class="btn-offset">
                    <button type="button" data-btn-layer-morph="" data-target="#layer-search" data-ripple="" class="btn btn-info btn-circle btn-lg shadow-z1"><em class="fa fa-search"></em></button>
                </div>
                <!-- START button offset-->
                <!-- START navbar header-->
                <div class="navbar-header">
                    <a href="{% if request.path == '/school/' or request.path == '/' %} javascript:viod(0) {% else %} / {% endif %}" class="navbar-brand">
                        <h3 class="brand-logo">Medicover School </h3>
                    </a>
                    <!-- Mobile buttons-->
                    <div class="mobile-toggles">
                        <!-- Button to show/hide the sidebar on mobile. Visible on mobile only.-->
                        <a href="#" class="sidebar-toggle"><em class="fa fa-navicon"></em></a>
                        <!-- Button to show/hide the header menu on mobile. Visible on mobile only.-->
                        <a href="#nav-collapse" data-toggle="collapse" class="menu-toggle hidden-material"><em class="fa fa-ellipsis-v fa-fw"></em></a>
                    </div>
                </div>
                <!-- END navbar header-->
                <!-- START Nav wrapper-->
                <div id="nav-collapse" class="nav-wrapper collapse navbar-collapse">
                    <!-- START Left navbar-->
                    <ul class="nav navbar-nav hidden-material">
                        <li>
                            <!-- Button used to collapse the left sidebar. Only visible on tablet and desktops-->
                            <a href="#" class="hidden-xs sidebar-toggle-off"><em class="fa fa-navicon"></em></a>
                        </li>

                        <!-- START lock screen-->
                        <!-- <li>
                            <a href="page.lock.html" title="Lock screen" data-ripple="">
                                <em class="icon-lock fa-fw"></em>
                                <span class="visible-xs-inline ml">Lock Screen </span>
                            </a>
                        </li> -->
                        <!-- END lock screen-->
                    </ul>
                    <ul class="nav navbar-nav hidden-material" style="float: right;">
                        <li class="dropdown"><a href="#" data-toggle="dropdown" data-ripple="" class="dropdown-toggle"><span class="fa fa-user"></span><span class="visible-xs-inline ml">{{ user }}</span></a>
                            <!-- START Dropdown menu-->
                            <ul id="bg-white" class="dropdown-menu p wd-lg" style="right:0;left:auto">
                                <li class="row ml0 mr0 mt mb text-center">
                                    <div class="col-xs-4">
                                        <div class="pv"><a href="{% url 'school:profile' %}"><span class="block mb"><em class="icon-head fa-2x text-warning"></em></span><small class="text-muted">Profile</small></a></div>
                                    </div>
                                    <div class="col-xs-4">
                                        <div class="pv"><a href="javascript:void(0)"><span class="block mb"><em class="icon-mail fa-2x text-primary"></em></span><small class="text-muted">Mailbox</small></a></div>
                                    </div>
                                    <div class="col-xs-4">
                                        <div class="pv"><a href="javascript:void(0)"><span class="block mb"><em class="icon-image fa-2x text-muted"></em></span><small class="text-muted">Gallery</small></a></div>
                                    </div>
                                    <div class="col-xs-4">
                                        <div class="pv">
                                            <div class="pv"><a href="{% url 'school:logout' %}"><span class="block mb"><span style="font-size: 30px" class="fa fa-sign-out"></span><small class="text-muted">Logout</small></a></div>
                                        </div>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                    <!-- END Left navbar-->
                </div>
                <!-- END Nav wrapper-->


            </nav>

templates/school/register.html
{% extends 'base.html' %} {% block content %}

<body>
    <div class="animated fadeOutZoom">
        <div class="container container-sm animated fadeInDown">
            <div class="center-block mt-xl">
                <!-- START panel-->
                <h3 style="text-align:center">Medicover School</h3>
                <div class="panel">
                    <div class="panel-body">
                        <p class="pv text-bold">REGISTER NEW PRINCIPAL ACCOUNT</p>
                        {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                        {% endif %}
                        <form role="form" class="mb-lg" action="" method="post">

                            {% csrf_token %} {% include 'school/form_register.html' %}
                        </form>
                    </div>
                </div>
                <!-- END panel-->
                <div class="p-lg text-center">
                    <hr><span class="mr-sm">&copy; </span><span class="mr-sm">2015</span><span>Naut</span><br>Bootstrap + AngularJS
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}